config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    #resources :following, :followers
    get 'following' , to: 'users#following'
    get 'followers' , to: 'users#followers'
    get 'page/:page', :action => :index, :on => :collection
    get 'likes' , to: 'users#likes'
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts do
     get 'page/:page', :action => :index, :on => :collection
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
  #get 'following' , to: 'users#following'
  #get 'followers' , to: 'users#followers'
  #resources :following do
  #  resources :ads
  #end
end

app/models/like.rb
class Like < ActiveRecord::Base
    #belongs_to :user
    #belongs_to :micropost
    belongs_to :likes, class_name: "Micropost"
    belongs_to :liked, class_name: "User"
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
     before_action :logged_in_user
     
    def create
        #binding.pry
        micropost_id= params[:micropost_id]
        @micropost = Micropost.find(micropost_id)
        current_user.like(@micropost)
        if @micropost.save
            flash[:success] = "Liked"
            redirect_to request.referrer || root_url
        else
            @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page])
            render 'static_pages/home'
        end

    end
     
    def destroy
        #binding.pry
        @like = current_user.likes_relationships.find(params[:id])
        return redirect_to root_url if @like.nil?
        @like.destroy
        flash[:success] = "Unliked"
        redirect_to request.referrer || root_url
    end
 
end

app/views/likes/_create.html.erb
<%= link_to likes_microposts_path(micropost_id: micropost.id), remote: true, method: :post, class: 'like-link' do %>
  <i class="fa fa-star unlike-star"></i>
<% end %>

app/views/likes/_destroy.html.erb
<%= link_to user_likes_path(current_user.likes.find_by(micropost.id)), remote: true, method: :delete, class: 'like-link' do %>
  <i class="fa fa-star like-star"></i>
<% end %>

app/views/likes/_likes_btn.html.erb
<% if current_user.likes(micropost) %>
    <%= render 'likes/destroy', micropost: micropost %>
<% else %>
    <%= render 'likes/create', micropost: micropost %>
<% end %>

app/views/likes/create.js.erb
$('#micropost<%= @micropost.id %>').html('<%= escape_javascript(render("like/like_btn", micropost: @micropost)) %>')
$('#like').text('<%= current_user.like.count %>')

app/views/likes/destroy.js.erb
$('#like_<%= @like.id %>').html('<%= escape_javascript(render("likes/like_btn", ,micropost: @micropost)) %>');
$('#like').text('<%= current_user.like.count %>');

app/views/likes/likes.html.erb
<div class ="row">

    <%= render @user %>

    <div class="col-md-8">
        <h1>Like</h1>
        <%= render @micropost %>
    </div>
</div>