config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    #resources :following, :followers
    get 'following' , to: 'users#following'
    get 'followers' , to: 'users#followers'
    get 'page/:page', :action => :index, :on => :collection
    get 'likes' , to: 'users#likes'
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts do
     get 'page/:page', :action => :index, :on => :collection
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
  #get 'following' , to: 'users#following'
  #get 'followers' , to: 'users#followers'
  #resources :following do
  #  resources :ads
  #end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :area, presence: false, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :microposts
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  has_many :likes
  has_many :likes_relationships, class_name: "Like",
                                  foreign_key: "liked_id",
                                  dependent: :destroy
  has_many :likes_users, through: :likes_relationships , source: :likes
  
  
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  # postをlikeする
  def like(micropost)
    likes_relationships.find_or_create_by(likes_id: micropost.id)
  end

  # likeしているpostをunlikeする
  def unlike(micropost)
    binding.pry
    likes_relationships = likes_relationships.find_by(id: lid)
    likes_relationships.destroy if likes_relationships
  end
  
  # あるpostをlikeしているかどうか？
  def likes?(micropost)
    #binding.pry
    #likes_users.include?(micropost)
    likes_relationships.find_by(likes_id: micropost)
  end
  
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit, :update, :following, :followers, :likes ]
  #before_action :user_params, only: [:edit, :update]
  before_action :user_params, only: [:update]
  
  def show
   @user = User.find(params[:id])
   #@microposts = @user.microposts.order(created_at: :desc)
   @microposts = @user.microposts.order(created_at: :desc).page(params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    #ログイン中useridとparamのuseridを比較
    if (@current_user.id != (params[:id]).to_i)
      redirect_to  root_path
    else
      #一致する場合はeditをeditにparamで引けるuser情報を表示
      #@user= User.find(params[:id])
      @user= User.find(current_user.id)
    end
  end
  
  def update
    if @current_user.update(user_params)
      flash[:success] = 'Your profile Updated'
      @user= User.find(current_user.id)
      render 'show'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def following
    @user = User.find(params[:user_id])
    @following = @user.following_users.page(params[:page])
    #@following = current_user.following_relationships
    render 'following'
  end
  
  def followers
    @user = User.find(params[:user_id])
    @followers = @user.follower_users.page(params[:page])
    #@followers = current_user.follower_relationships
    render 'followers'
  end
  
  def likes
    @user = User.find(params[:user_id])
    @micropost = @user.likes_users.page(params[:page])
    render 'likes/likes'
    #render 'shared/feeds'
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :area, :password, :password_confirmation, :page)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@current_user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email  %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :area %>
      <%= f.text_field :area, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Submmit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_form_new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :area %>
      <%= f.text_field :area, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Submmit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_likes.html.erb
<h1>Like</h1>

<%= render @micropost %>

<h1>Users</h1>

<%= will_paginate @users %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<aside class="col-md-4">
    <section class="user_info">
        <h1>
            <%= gravatar_for user %>
            <%= link_to user.name, user_path(user) %>
        </h1>
    </section>
</aside>

app/views/users/_user_info.html.erb
<aside class="col-md-4">
    <section class="user_info">
        <h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
        </h1>
    </section>
    <span>following:<%= link_to @user.following_users.count, user_following_path(user_id:@user) %></span>
    <span>followers:<%= link_to @user.follower_users.count, user_followers_path(user_id:@user) %></span>
    <div>likes:<%= link_to @user.likes_relationships.count, user_likes_path(user_id:@user) %></div>
</aside>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<%= render 'form' %>

app/views/users/followers.html.erb
<div class="row">
  <%= render @user %>
  <h1>followers</h1>

  <div class="col-md-8">
    <%= render @followers %>
    <%= paginate @followers %>
  </div>
</div>

app/views/users/following.html.erb
<div class="row">
    <%= render @user %>
    <h1>following</h1>

    <div class="col-md-8">
        <%= render @following %>
        <%= paginate @following %>
    </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form_new' %>

app/views/users/show.html.erb
<div class="row">
  <%= render 'user_info' %>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
    <%= paginate @microposts %>
  </div>
</div>